version: '3.1'
services:
  postgres:
    image: "postgres:10"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marketplace
      - POSTGRES_PORT=5432
    ports:
      # map to 5433 to prevent interference with local installation of postgres
      - "5433:5432"
volumes:
  postgres:
